/**
 * @file assets plugin, build time — the two output files as strings: `manifest.json` for the
 * plugin (the dev one of the scanner and the packed one of the packer) and `generated/assets.ts`
 * for the compiler. Both are sorted and carry no timestamp, no absolute path and no machine data,
 * so two runs on the same tree write the same bytes.
 */
import type {
  AssetKind,
  AtlasFrame,
  AtlasPage,
  FontPage,
  Manifest,
  ManifestBundle,
  ManifestFile,
  NineSlice,
  Tier
} from "../types";

const HEADER = "// generated by @moku-labs/game/assets, do not edit";

/** How the generated table ends, so the keys stay literal types for the game. */
const FROZEN = " as const;";

/** One key that carries nine-slice metadata. */
type NineEntry = { key: string; nine: NineSlice };

/**
 * One file entry of `manifest.json`, as written: a `ManifestFile` without the fields it does not
 * carry. A font and a sound have no size, a texture has no kind, a packed texture has no path.
 */
type PlainFile = {
  key: string;
  path?: string;
  kind?: AssetKind;
  width?: number;
  height?: number;
  mb: number;
  pages?: FontPage[];
  nine?: NineSlice;
  atlas?: AtlasFrame;
};

/** One atlas page of `manifest.json`, as written: the fields of `AtlasPage` in a fixed order. */
type PlainPage = { id: string; path: string; width: number; height: number; mb: number };

/** One bundle of `manifest.json`, as written: a `ManifestBundle` with plain pages and files. */
type PlainBundle = {
  feature: string;
  tier: Tier;
  mb: number;
  pages?: PlainPage[];
  files: PlainFile[];
};

/** The whole of `manifest.json`, as written: a `Manifest` with plain bundles. */
type PlainManifest = { version: Manifest["version"]; bundles: Record<string, PlainBundle> };

/**
 * Compares two names, so every list the scanner writes has one order.
 *
 * @param left - First name.
 * @param right - Second name.
 * @returns The sort order.
 */
function byName(left: string, right: string): number {
  return left.localeCompare(right);
}

/**
 * Writes one file entry in the field order of the manifest: `key`, `path`, `kind`, `width`,
 * `height`, `mb`, `pages`, `nine`, `atlas`. A field the file does not carry is left out: a
 * texture says nothing about its kind, which keeps a manifest written before fonts and audio
 * readable, and a texture packed in an atlas has no `path`. A font and a sound carry no size.
 *
 * @param file - The file.
 * @returns The entry as JSON data.
 */
function plainFile(file: ManifestFile): PlainFile {
  const kind = file.kind ?? "texture";
  const path = file.path === undefined ? {} : { path: file.path };

  if (kind !== "texture") {
    return {
      key: file.key,
      ...path,
      kind,
      mb: file.mb,
      ...(file.pages === undefined ? {} : { pages: file.pages.map(page => ({ ...page })) })
    };
  }

  return {
    key: file.key,
    ...path,
    width: file.width,
    height: file.height,
    mb: file.mb,
    ...(file.nine === undefined ? {} : { nine: file.nine }),
    ...(file.atlas === undefined ? {} : { atlas: { ...file.atlas } })
  };
}

/**
 * Writes one atlas page with a fixed field order.
 *
 * @param page - The page.
 * @returns The page as JSON data.
 */
function plainPage(page: AtlasPage): PlainPage {
  return { id: page.id, path: page.path, width: page.width, height: page.height, mb: page.mb };
}

/**
 * Writes one bundle with a fixed field order, its pages sorted by id when it has any and its
 * files sorted by key.
 *
 * @param bundle - The bundle.
 * @returns The bundle as JSON data.
 */
function plainBundle(bundle: ManifestBundle): PlainBundle {
  const pages = bundle.pages
    ?.toSorted((left, right) => byName(left.id, right.id))
    .map(page => plainPage(page));

  return {
    feature: bundle.feature,
    tier: bundle.tier,
    mb: bundle.mb,
    ...(pages === undefined ? {} : { pages }),
    files: bundle.files
      .toSorted((left, right) => byName(left.key, right.key))
      .map(file => plainFile(file))
  };
}

/**
 * Lists the bundle names of a manifest, sorted.
 *
 * @param manifest - The manifest.
 * @returns The names.
 */
function bundleNames(manifest: Manifest): string[] {
  return Object.keys(manifest.bundles).toSorted(byName);
}

/**
 * Lists the bundles of a manifest with their names, sorted by name.
 *
 * @param manifest - The manifest.
 * @returns The pairs.
 */
function sortedBundles(manifest: Manifest): [string, ManifestBundle][] {
  return Object.entries(manifest.bundles).toSorted((left, right) => byName(left[0], right[0]));
}

/**
 * Lists every file of a manifest, bundle by bundle in name order.
 *
 * @param manifest - The manifest.
 * @returns The files.
 */
function allFiles(manifest: Manifest): ManifestFile[] {
  const files: ManifestFile[] = [];

  for (const [, bundle] of sortedBundles(manifest)) files.push(...bundle.files);

  return files;
}

/**
 * Writes one union type, or `never` when the game has no key of that kind yet.
 *
 * @param name - Name of the type.
 * @param values - The members, in any order.
 * @returns The declaration.
 */
function union(name: string, values: readonly string[]): string {
  const members = [...new Set(values)].toSorted(byName);

  if (members.length === 0) return `export type ${name} = never;`;

  const lines = members.map(member => `  | "${member}"`).join("\n");

  return `export type ${name} =\n${lines};`;
}

/**
 * Lists the keys of one kind. They are the narrow unions a text style and a sound are typed by,
 * so a texture key does not compile where a font is meant.
 *
 * @param files - Every file of the manifest.
 * @param kind - The kind to collect.
 * @returns The asset keys of that kind.
 * @example
 * ```ts
 * keysOfKind([{ key: "ui.body", path: "b.fnt", kind: "font", width: 0, height: 0, mb: 0 }], "font");
 * // ["ui.body"]
 * ```
 */
function keysOfKind(files: readonly ManifestFile[], kind: AssetKind): string[] {
  return files.filter(file => file.kind === kind).map(file => file.key);
}

/**
 * Writes the nine-slice table the kit reads when it builds a nine-slice sprite.
 *
 * @param entries - The keys that carry borders.
 * @returns The declaration.
 */
function nineTable(entries: readonly NineEntry[]): string {
  if (entries.length === 0) return `export const nineSlice = {}${FROZEN}`;

  const rows = entries
    .toSorted((left, right) => byName(left.key, right.key))
    .map(
      ({ key, nine }) =>
        `  "${key}": { left: ${nine.left}, top: ${nine.top}, ` +
        `right: ${nine.right}, bottom: ${nine.bottom} }`
    );

  return `export const nineSlice = {\n${rows.join(",\n")}\n}${FROZEN}`;
}

/**
 * Writes `manifest.json`: two-space JSON with a trailing newline, bundles sorted by name, pages
 * by id and files by key. The version is written as given: `1` from the scanner, `2` from the
 * packer.
 *
 * @param manifest - What the scan produced.
 * @returns The text of the file.
 * @example
 * ```ts
 * emitManifest({ version: 1, bundles: {} }); // '{\n  "version": 1,\n  "bundles": {}\n}\n'
 * ```
 */
export function emitManifest(manifest: Manifest): string {
  const bundles: Record<string, PlainBundle> = {};

  for (const [name, bundle] of sortedBundles(manifest)) bundles[name] = plainBundle(bundle);

  const plain: PlainManifest = { version: manifest.version, bundles };

  return `${JSON.stringify(plain, undefined, 2)}\n`;
}

/**
 * Writes `generated/assets.ts`: `AssetKey` over every kind, the narrower `FontKey` and `AudioKey`
 * next to it, `BundleKey`, and the nine-slice table. A game commits this file, so `defineGame` can
 * type `Sprite`, a text style, a sound, `defineBundles` and the `load` effect from it.
 *
 * @param manifest - What the scan produced.
 * @returns The text of the module.
 * @example
 * ```ts
 * emitKeys({ version: 1, bundles: {} });
 * // the header, four unions that are all "never" and an empty nine-slice table
 * ```
 */
export function emitKeys(manifest: Manifest): string {
  const files = allFiles(manifest);
  const nine: NineEntry[] = [];

  for (const file of files) {
    if (file.nine !== undefined) nine.push({ key: file.key, nine: file.nine });
  }

  const blocks = [
    HEADER,
    union(
      "AssetKey",
      files.map(file => file.key)
    ),
    union("FontKey", keysOfKind(files, "font")),
    union("AudioKey", keysOfKind(files, "audio")),
    union("BundleKey", bundleNames(manifest)),
    nineTable(nine)
  ];

  return `${blocks.join("\n\n")}\n`;
}
