/**
 * @file assets plugin, build time — the two output files as strings: `manifest.json` for the
 * plugin and `generated/assets.ts` for the compiler. Both are sorted and carry no timestamp, no
 * absolute path and no machine data, so two scans of the same tree write the same bytes.
 */
import type { Manifest, ManifestBundle, ManifestFile, NineSlice } from "../types";

const HEADER = "// generated by @moku-labs/game/assets-scan, do not edit";

/** How the generated table ends, so the keys stay literal types for the game. */
const FROZEN = " as const;";

/** One key that carries nine-slice metadata. */
type NineEntry = { key: string; nine: NineSlice };

/**
 * Compares two names, so every list the scanner writes has one order.
 *
 * @param left - First name.
 * @param right - Second name.
 * @returns The sort order.
 */
function byName(left: string, right: string): number {
  return left.localeCompare(right);
}

/**
 * Writes one file entry with a fixed field order. The reserved `atlas` field is dropped: this
 * version never packs an atlas.
 *
 * @param file - The file.
 * @returns The entry as JSON data.
 */
function plainFile(file: ManifestFile): Record<string, unknown> {
  return {
    key: file.key,
    path: file.path,
    width: file.width,
    height: file.height,
    mb: file.mb,
    ...(file.nine === undefined ? {} : { nine: file.nine })
  };
}

/**
 * Writes one bundle with a fixed field order and its files sorted by key.
 *
 * @param bundle - The bundle.
 * @returns The bundle as JSON data.
 */
function plainBundle(bundle: ManifestBundle): Record<string, unknown> {
  return {
    feature: bundle.feature,
    tier: bundle.tier,
    mb: bundle.mb,
    files: bundle.files
      .toSorted((left, right) => byName(left.key, right.key))
      .map(file => plainFile(file))
  };
}

/**
 * Lists the bundle names of a manifest, sorted.
 *
 * @param manifest - The manifest.
 * @returns The names.
 */
function bundleNames(manifest: Manifest): string[] {
  return Object.keys(manifest.bundles).toSorted(byName);
}

/**
 * Lists the bundles of a manifest with their names, sorted by name.
 *
 * @param manifest - The manifest.
 * @returns The pairs.
 */
function sortedBundles(manifest: Manifest): [string, ManifestBundle][] {
  return Object.entries(manifest.bundles).toSorted((left, right) => byName(left[0], right[0]));
}

/**
 * Lists every file of a manifest, bundle by bundle in name order.
 *
 * @param manifest - The manifest.
 * @returns The files.
 */
function allFiles(manifest: Manifest): ManifestFile[] {
  const files: ManifestFile[] = [];

  for (const [, bundle] of sortedBundles(manifest)) files.push(...bundle.files);

  return files;
}

/**
 * Writes one union type, or `never` when the game has no key of that kind yet.
 *
 * @param name - Name of the type.
 * @param values - The members, in any order.
 * @returns The declaration.
 */
function union(name: string, values: readonly string[]): string {
  const members = [...new Set(values)].toSorted(byName);

  if (members.length === 0) return `export type ${name} = never;`;

  const lines = members.map(member => `  | "${member}"`).join("\n");

  return `export type ${name} =\n${lines};`;
}

/**
 * Writes the nine-slice table the kit reads when it builds a nine-slice sprite.
 *
 * @param entries - The keys that carry borders.
 * @returns The declaration.
 */
function nineTable(entries: readonly NineEntry[]): string {
  if (entries.length === 0) return `export const nineSlice = {}${FROZEN}`;

  const rows = entries
    .toSorted((left, right) => byName(left.key, right.key))
    .map(
      ({ key, nine }) =>
        `  "${key}": { left: ${nine.left}, top: ${nine.top}, ` +
        `right: ${nine.right}, bottom: ${nine.bottom} }`
    );

  return `export const nineSlice = {\n${rows.join(",\n")}\n}${FROZEN}`;
}

/**
 * Writes `manifest.json`: two-space JSON with a trailing newline, bundles sorted by name and
 * files sorted by key.
 *
 * @param manifest - What the scan produced.
 * @returns The text of the file.
 * @example
 * ```ts
 * emitManifest({ version: 1, bundles: {} }); // '{\n  "version": 1,\n  "bundles": {}\n}\n'
 * ```
 */
export function emitManifest(manifest: Manifest): string {
  const bundles: Record<string, unknown> = {};

  for (const [name, bundle] of sortedBundles(manifest)) bundles[name] = plainBundle(bundle);

  return `${JSON.stringify({ version: manifest.version, bundles }, undefined, 2)}\n`;
}

/**
 * Writes `generated/assets.ts`: the two key unions and the nine-slice table. A game commits this
 * file, so `defineGame` can type `Sprite`, `defineBundles` and the `load` effect from it.
 *
 * @param manifest - What the scan produced.
 * @returns The text of the module.
 * @example
 * ```ts
 * emitKeys({ version: 1, bundles: {} });
 * // the header, "export type AssetKey = never;" and an empty nine-slice table
 * ```
 */
export function emitKeys(manifest: Manifest): string {
  const files = allFiles(manifest);
  const nine: NineEntry[] = [];

  for (const file of files) {
    if (file.nine !== undefined) nine.push({ key: file.key, nine: file.nine });
  }

  const blocks = [
    HEADER,
    union(
      "AssetKey",
      files.map(file => file.key)
    ),
    union("BundleKey", bundleNames(manifest)),
    nineTable(nine)
  ];

  return `${blocks.join("\n\n")}\n`;
}
