import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { checkStrings, compileStrings } from "../../compile/compile";
import { createIntlKit } from "../../intl";
import { evaluateModule } from "./evaluate";

const ORDERS_RU = "{n, plural, one {# заказ} few {# заказа} many {# заказов} other {# заказа}}";

const ORDERS_EN = "{n, plural, one {# order} other {# orders}}";

const TABS_RU = "{id, select, audio {Звук} language {Язык} other {Вкладка}}";

const EXPECTED_TYPES = `// generated by @moku-labs/game/assets, do not edit
import type { DescriptionNode } from "@moku-labs/game";

type Argument = string | number | readonly string[] | DescriptionNode;

export type Strings = {
  "hud.coins": { icon: Argument; n: number };
  "hud.orders": { n: number };
  "hud.title": Record<string, never>;
  "orders.coins": { n: number };
  "settings.tab": { id: "audio" | "language" };
};

export type StringKey = keyof Strings;
`;

/**
 * Creates an empty game source root in the system temp folder.
 *
 * @returns The path of the root.
 */
async function createRoot(): Promise<string> {
  return await mkdtemp(path.join(tmpdir(), "moku-i18n-"));
}

/**
 * Writes one string file of one feature.
 *
 * @param root - The game source root.
 * @param feature - Name of the feature.
 * @param locale - The locale.
 * @param table - The messages, or the raw text of the file.
 * @returns The path of the file, relative to the root.
 */
async function write(
  root: string,
  feature: string,
  locale: string,
  table: Record<string, unknown> | string
): Promise<string> {
  const folder = path.join(root, "features", feature, "strings");

  await mkdir(folder, { recursive: true });

  const text = typeof table === "string" ? table : `${JSON.stringify(table, undefined, 2)}\n`;

  await writeFile(path.join(folder, `${locale}.json`), text);

  return path.join("features", feature, "strings", `${locale}.json`);
}

/**
 * Writes the fixture game: three features, two locales, one key only Russian has.
 *
 * @returns The root and the generated folder.
 */
async function fixture(): Promise<{ root: string; out: string }> {
  const root = await createRoot();

  await write(root, "hud", "ru", {
    "hud.orders": ORDERS_RU,
    "hud.coins": "{icon} {n, number}",
    "hud.title": "Заказы"
  });
  await write(root, "hud", "en", {
    "hud.orders": ORDERS_EN,
    "hud.coins": "{icon} {n, number}",
    "hud.title": "Orders"
  });
  await write(root, "orders", "ru", { "orders.coins": "Награда: {n, number} монет" });
  await write(root, "orders", "en", { "orders.coins": "Reward: {n, number} coins" });
  await write(root, "settings", "ru", { "settings.tab": TABS_RU });

  return { root, out: path.join(root, "generated") };
}

describe("compileStrings", () => {
  it("reports every locale and every key, sorted", async () => {
    const { root, out } = await fixture();
    const report = await compileStrings(root, out);

    expect(report.changed).toBe(true);
    expect(report.locales).toEqual(["en", "ru"]);
    expect(report.keys).toEqual([
      "hud.coins",
      "hud.orders",
      "hud.title",
      "orders.coins",
      "settings.tab"
    ]);
  });

  it("writes the types module with the parameters of every locale", async () => {
    const { root, out } = await fixture();

    await compileStrings(root, out);

    expect(await readFile(path.join(out, "strings.ts"), "utf8")).toBe(EXPECTED_TYPES);
  });

  it("writes one compiled module per locale, keys sorted", async () => {
    const { root, out } = await fixture();

    await compileStrings(root, out);

    const source = await readFile(path.join(out, "strings.ru.ts"), "utf8");

    expect(source.startsWith("// generated by @moku-labs/game/assets, do not edit\n")).toBe(true);
    expect(source.endsWith("\n")).toBe(true);

    const messages = evaluateModule(source);

    expect(Object.keys(messages)).toEqual([
      "hud.coins",
      "hud.orders",
      "hud.title",
      "orders.coins",
      "settings.tab"
    ]);
    expect(messages["hud.orders"]?.({ n: 3 }, createIntlKit("ru"))).toEqual([
      { kind: "text", text: "3 заказа" }
    ]);
  });

  it("warns about a key one locale lacks and still compiles", async () => {
    const { root, out } = await fixture();
    const report = await compileStrings(root, out);
    const english = evaluateModule(await readFile(path.join(out, "strings.en.ts"), "utf8"));

    expect(report.notes).toEqual([
      'the key "settings.tab" is missing from features/settings/strings/en.json.'
    ]);
    expect(Object.keys(english)).not.toContain("settings.tab");
  });

  it("writes the same bytes on a second run and reports no change", async () => {
    const { root, out } = await fixture();

    await compileStrings(root, out);

    const first = await readFile(path.join(out, "strings.ru.ts"), "utf8");
    const report = await compileStrings(root, out);

    expect(report.changed).toBe(false);
    expect(await readFile(path.join(out, "strings.ru.ts"), "utf8")).toBe(first);
  });

  it("writes nothing for a game with no features folder", async () => {
    const root = await createRoot();
    const report = await compileStrings(root, path.join(root, "generated"));

    expect(report).toEqual({ changed: false, locales: [], keys: [], notes: [] });
    await expect(readFile(path.join(root, "generated", "strings.ts"), "utf8")).rejects.toThrow();
  });

  it("writes nothing on a check run and reports the difference", async () => {
    const { root, out } = await fixture();
    const report = await compileStrings(root, out, { check: true });

    expect(report.changed).toBe(true);
    await expect(readFile(path.join(out, "strings.ts"), "utf8")).rejects.toThrow();
  });
});

describe("compileStrings problems", () => {
  it("names the key and the file of an unsupported ICU feature", async () => {
    const root = await createRoot();
    const file = await write(root, "hud", "ru", { "hud.price": "{n, number, currency}" });

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `[game] i18n: "hud.price" in ${file}: the number style "currency" is not supported.\n` +
        "  Fix the message or use a supported ICU feature."
    );
  });

  it("lists every problem in one error", async () => {
    const root = await createRoot();

    await write(root, "hud", "ru", {
      "hud.price": "{n, number, currency}",
      "hud.orders": "{n, plural, one {#}}"
    });

    const failure = await compileStrings(root, path.join(root, "generated")).catch(
      (error: unknown) => error
    );

    expect(String(failure)).toContain("the compile found 2 problems");
    expect(String(failure)).toContain('"hud.price"');
    expect(String(failure)).toContain('"hud.orders"');
  });

  it("names both files when two features carry the same key", async () => {
    const root = await createRoot();
    const hud = await write(root, "hud", "ru", { "hud.orders": ORDERS_RU });
    const orders = await write(root, "orders", "ru", { "hud.orders": ORDERS_RU });

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `the key "hud.orders" is in ${hud} and ${orders}`
    );
  });

  it("names both files when one parameter has two argument kinds", async () => {
    const root = await createRoot();
    const russian = await write(root, "hud", "ru", { "hud.orders": ORDERS_RU });
    const english = await write(root, "hud", "en", {
      "hud.orders": "{n, select, a {a} other {b}}"
    });

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `"hud.orders": the parameter "n" is a select in ${english} and a number in ${russian}`
    );
  });

  it("names the file of a message that is not a string", async () => {
    const root = await createRoot();
    const file = await write(root, "hud", "ru", { "hud.orders": { nested: "no" } });

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `"hud.orders" in ${file}: a message must be a string.`
    );
  });

  it("names the file of a table that is not an object", async () => {
    const root = await createRoot();
    const file = await write(root, "hud", "ru", '["hud.orders"]\n');

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `${file}: a string file is an object of key to message.`
    );
  });

  it("names the file it could not read", async () => {
    const root = await createRoot();
    const file = await write(root, "hud", "ru", "{ not json\n");

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `${file} could not be read`
    );
  });
});

describe("checkStrings", () => {
  it("answers false while the generated modules are stale, then true", async () => {
    const { root, out } = await fixture();

    expect(await checkStrings(root, out)).toBe(false);

    await compileStrings(root, out);

    expect(await checkStrings(root, out)).toBe(true);
  });
});
