import { describe, expect, it } from "vitest";
import { emitLocale, emitTypes } from "../../compile/emit";
import { compileMessage } from "../../compile/message";
import { createIntlKit, messageDuration } from "../../intl";
import type { IntlKit } from "../../types";
import { evaluateModule } from "./evaluate";

/** The import line of a module whose messages need the duration helper only. */
const DURATION_IMPORT = 'import { messageDuration as duration } from "@moku-labs/game";';

/** The import line of a module whose messages need the argument helper only. */
const ARGUMENT_IMPORT = 'import { messageArgument as argument } from "@moku-labs/game";';

/** The import line of a module whose messages need both helpers. */
const BOTH_IMPORT =
  'import { messageArgument as argument, messageDuration as duration } from "@moku-labs/game";';

/**
 * A duration "format" that writes back the record it was handed.
 *
 * @param input - What the emitted helper built.
 * @returns The record as JSON.
 */
function format(input: object): string {
  return JSON.stringify(input);
}

/**
 * A kit whose duration formatter writes back the record it was handed, so a test reads what the
 * emitted helper produced.
 *
 * @returns The kit of "en" with a recording `duration`.
 */
function recordingKit(): IntlKit {
  return { ...createIntlKit("en"), duration: () => ({ format }) as unknown as Intl.DurationFormat };
}

/**
 * Runs the emitted `duration` helper on one value.
 *
 * @param ms - Milliseconds.
 * @returns The record the helper built, as JSON.
 */
function helperOf(ms: number): string {
  const module = evaluateModule(
    emitLocale([{ key: "chest.opens", compiled: compileMessage("{left, duration}") }])
  );
  const parts = module["chest.opens"]?.({ left: ms }, recordingKit()) ?? [];

  return parts.map(part => (part.kind === "text" ? part.text : "")).join("");
}

describe("the helpers of a locale module", () => {
  it("imports the duration helper from the engine once when several messages need it", () => {
    const source = emitLocale([
      { key: "chest.opens", compiled: compileMessage("Opens in {left, duration}") },
      { key: "energy.refill", compiled: compileMessage("Refills in {time, duration, long}") }
    ]);

    expect(source.split(DURATION_IMPORT)).toHaveLength(2);
    expect(source).not.toContain("function duration(");
    expect(source).not.toContain("messageArgument");
  });

  it("imports the argument helper from the engine and inlines no function", () => {
    const source = emitLocale([
      { key: "hud.coins", compiled: compileMessage("{icon} {n, number}") }
    ]);

    expect(source).toContain(ARGUMENT_IMPORT);
    expect(source).not.toContain("function argument(");
    expect(source).not.toContain("messageDuration");
    expect(source).toContain("argument(p.icon, intl)");
  });

  it("imports nothing but the types when no message needs a helper", () => {
    const source = emitLocale([{ key: "hud.coins", compiled: compileMessage("{n, number}") }]);

    expect(source).toBe(
      [
        "// generated by @moku-labs/game/assets, do not edit",
        'import type { I18n } from "@moku-labs/game";',
        "",
        "export default {",
        '  "hud.coins": (p, intl) => [{ kind: "text", text: intl.number().format(p.n as number) }]',
        "} satisfies I18n.CompiledMessages;",
        ""
      ].join("\n")
    );
  });

  it("imports both helpers in one line, under the type import, when both are needed", () => {
    const source = emitLocale([
      { key: "chest.opens", compiled: compileMessage("{name} opens in {left, duration}") }
    ]);

    expect(source.split("\n").slice(0, 3)).toEqual([
      "// generated by @moku-labs/game/assets, do not edit",
      'import type { I18n } from "@moku-labs/game";',
      BOTH_IMPORT
    ]);
    expect(source).toContain("duration(p.left as number)");
    expect(source).not.toMatch(/function (?:argument|duration)\(/);
  });

  it("builds the record Intl.DurationFormat reads", () => {
    expect(helperOf(95_000)).toBe('{"minutes":1,"seconds":35}');
    expect(helperOf(3_605_000)).toBe('{"hours":1,"seconds":5}');
    expect(helperOf(0)).toBe('{"seconds":0}');
  });

  it.each([
    0,
    1,
    500,
    999,
    1000,
    59_001,
    60_000,
    95_000,
    3_600_000,
    7_295_000,
    -5,
    Number.NaN
  ])("splits %d ms the way messageDuration does", ms => {
    expect(helperOf(ms)).toBe(JSON.stringify(messageDuration(ms)));
  });

  it("splits an infinite value the way messageDuration does", () => {
    expect(helperOf(Number.POSITIVE_INFINITY)).toBe(
      JSON.stringify(messageDuration(Number.POSITIVE_INFINITY))
    );
  });
});

describe("the types module", () => {
  it("types a duration parameter as milliseconds", () => {
    const source = emitTypes([{ key: "chest.opens", params: { left: { kind: "duration" } } }]);

    expect(source).toContain('  "chest.opens": { left: number };');
    expect(source).not.toContain("DescriptionNode");
  });
});
