import { mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { checkStrings, compileStrings } from "../../compile/compile";
import { createIntlKit } from "../../intl";
import { evaluateModule } from "./evaluate";

const ORDERS_RU = "{n, plural, one {# заказ} few {# заказа} many {# заказов} other {# заказа}}";

const ORDERS_EN = "{n, plural, one {# order} other {# orders}}";

const TABS_RU = "{id, select, audio {Звук} language {Язык} other {Вкладка}}";

const EXPECTED_TYPES = `// generated by @moku-labs/game/assets, do not edit
import type { DescriptionNode } from "@moku-labs/game";

type Argument = string | number | readonly string[] | DescriptionNode;

export type Strings = {
  "hud.coins": { icon: Argument; n: number };
  "hud.orders": { n: number };
  "hud.title": Record<string, never>;
  "orders.coins": { n: number };
  "settings.tab": { id: "audio" | "language" };
};

export type StringKey = keyof Strings;
`;

/**
 * Creates an empty game source root in the system temp folder.
 *
 * @returns The path of the root.
 */
async function createRoot(): Promise<string> {
  return await mkdtemp(path.join(tmpdir(), "moku-i18n-"));
}

/**
 * Writes one string file of one owner folder: a feature folder or a layer.
 *
 * @param root - The game source root.
 * @param owner - POSIX path of the owner folder under the root, `features/hud` or `shared`.
 * @param locale - The locale.
 * @param table - The messages, or the raw text of the file.
 * @returns The POSIX path of the file, relative to the root.
 */
async function writeIn(
  root: string,
  owner: string,
  locale: string,
  table: Record<string, unknown> | string
): Promise<string> {
  const folder = path.join(root, ...owner.split("/"), "strings");

  await mkdir(folder, { recursive: true });

  const text = typeof table === "string" ? table : `${JSON.stringify(table, undefined, 2)}\n`;

  await writeFile(path.join(folder, `${locale}.json`), text);

  return `${owner}/strings/${locale}.json`;
}

/**
 * Writes one string file of one feature.
 *
 * @param root - The game source root.
 * @param feature - Name of the feature.
 * @param locale - The locale.
 * @param table - The messages, or the raw text of the file.
 * @returns The path of the file, relative to the root.
 */
async function write(
  root: string,
  feature: string,
  locale: string,
  table: Record<string, unknown> | string
): Promise<string> {
  return await writeIn(root, `features/${feature}`, locale, table);
}

/**
 * Writes the fixture game: three features, two locales, one key only Russian has.
 *
 * @returns The root and the generated folder.
 */
async function fixture(): Promise<{ root: string; out: string }> {
  const root = await createRoot();

  await write(root, "hud", "ru", {
    "hud.orders": ORDERS_RU,
    "hud.coins": "{icon} {n, number}",
    "hud.title": "Заказы"
  });
  await write(root, "hud", "en", {
    "hud.orders": ORDERS_EN,
    "hud.coins": "{icon} {n, number}",
    "hud.title": "Orders"
  });
  await write(root, "orders", "ru", { "orders.coins": "Награда: {n, number} монет" });
  await write(root, "orders", "en", { "orders.coins": "Reward: {n, number} coins" });
  await write(root, "settings", "ru", { "settings.tab": TABS_RU });

  return { root, out: path.join(root, "generated") };
}

describe("compileStrings", () => {
  it("reports every locale and every key, sorted", async () => {
    const { root, out } = await fixture();
    const report = await compileStrings(root, out);

    expect(report.changed).toBe(true);
    expect(report.locales).toEqual(["en", "ru"]);
    expect(report.keys).toEqual([
      "hud.coins",
      "hud.orders",
      "hud.title",
      "orders.coins",
      "settings.tab"
    ]);
  });

  it("writes the types module with the parameters of every locale", async () => {
    const { root, out } = await fixture();

    await compileStrings(root, out);

    expect(await readFile(path.join(out, "strings.ts"), "utf8")).toBe(EXPECTED_TYPES);
  });

  it("writes one compiled module per locale, keys sorted", async () => {
    const { root, out } = await fixture();

    await compileStrings(root, out);

    const source = await readFile(path.join(out, "strings.ru.ts"), "utf8");

    expect(source.startsWith("// generated by @moku-labs/game/assets, do not edit\n")).toBe(true);
    expect(source.endsWith("\n")).toBe(true);

    const messages = evaluateModule(source);

    expect(Object.keys(messages)).toEqual([
      "hud.coins",
      "hud.orders",
      "hud.title",
      "orders.coins",
      "settings.tab"
    ]);
    expect(messages["hud.orders"]?.({ n: 3 }, createIntlKit("ru"))).toEqual([
      { kind: "text", text: "3 заказа" }
    ]);
  });

  it("warns about a key one locale lacks and still compiles", async () => {
    const { root, out } = await fixture();
    const report = await compileStrings(root, out);
    const english = evaluateModule(await readFile(path.join(out, "strings.en.ts"), "utf8"));

    expect(report.notes).toEqual([
      'the key "settings.tab" is missing from features/settings/strings/en.json.'
    ]);
    expect(Object.keys(english)).not.toContain("settings.tab");
  });

  it("writes the same bytes on a second run and reports no change", async () => {
    const { root, out } = await fixture();

    await compileStrings(root, out);

    const first = await readFile(path.join(out, "strings.ru.ts"), "utf8");
    const report = await compileStrings(root, out);

    expect(report.changed).toBe(false);
    expect(await readFile(path.join(out, "strings.ru.ts"), "utf8")).toBe(first);
  });

  it("writes nothing for a game with no features folder", async () => {
    const root = await createRoot();
    const report = await compileStrings(root, path.join(root, "generated"));

    expect(report).toEqual({ changed: false, locales: [], keys: [], notes: [] });
    await expect(readFile(path.join(root, "generated", "strings.ts"), "utf8")).rejects.toThrow();
  });

  it("writes nothing on a check run and reports the difference", async () => {
    const { root, out } = await fixture();
    const report = await compileStrings(root, out, { check: true });

    expect(report.changed).toBe(true);
    await expect(readFile(path.join(out, "strings.ts"), "utf8")).rejects.toThrow();
  });
});

describe("compileStrings problems", () => {
  it("names the key and the file of an unsupported ICU feature", async () => {
    const root = await createRoot();
    const file = await write(root, "hud", "ru", { "hud.price": "{n, number, currency}" });

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `[game] i18n: "hud.price" in ${file}: the number style "currency" is not supported.\n` +
        "  Fix the message or use a supported ICU feature."
    );
  });

  it("lists every problem in one error", async () => {
    const root = await createRoot();

    await write(root, "hud", "ru", {
      "hud.price": "{n, number, currency}",
      "hud.orders": "{n, plural, one {#}}"
    });

    const failure = await compileStrings(root, path.join(root, "generated")).catch(
      (error: unknown) => error
    );

    expect(String(failure)).toContain("the compile found 2 problems");
    expect(String(failure)).toContain('"hud.price"');
    expect(String(failure)).toContain('"hud.orders"');
  });

  it("names both files when two features carry the same key", async () => {
    const root = await createRoot();
    const hud = await write(root, "hud", "ru", { "hud.orders": ORDERS_RU });
    const orders = await write(root, "orders", "ru", { "hud.orders": ORDERS_RU });

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `the key "hud.orders" is in ${hud} and ${orders}`
    );
  });

  it("names both files when one parameter has two argument kinds", async () => {
    const root = await createRoot();
    const russian = await write(root, "hud", "ru", { "hud.orders": ORDERS_RU });
    const english = await write(root, "hud", "en", {
      "hud.orders": "{n, select, a {a} other {b}}"
    });

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `"hud.orders": the parameter "n" is a select in ${english} and a number in ${russian}`
    );
  });

  it("names the file of a message that is not a string", async () => {
    const root = await createRoot();
    const file = await write(root, "hud", "ru", { "hud.orders": { nested: "no" } });

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `"hud.orders" in ${file}: a message is a string or { "text": string, "note": string }.`
    );
  });

  it("names the file of a table that is not an object", async () => {
    const root = await createRoot();
    const file = await write(root, "hud", "ru", '["hud.orders"]\n');

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `${file}: a string file is an object of key to message.`
    );
  });

  it("names the file it could not read", async () => {
    const root = await createRoot();
    const file = await write(root, "hud", "ru", "{ not json\n");

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `${file} could not be read`
    );
  });
});

describe("checkStrings", () => {
  it("answers false while the generated modules are stale, then true", async () => {
    const { root, out } = await fixture();

    expect(await checkStrings(root, out)).toBe(false);

    await compileStrings(root, out);

    expect(await checkStrings(root, out)).toBe(true);
  });
});

describe("compileStrings with durations", () => {
  it("types a duration parameter as a number", async () => {
    const root = await createRoot();
    const out = path.join(root, "generated");

    await write(root, "chest", "en", { "chest.opens": "Opens in {left, duration, short}" });
    await compileStrings(root, out);

    expect(await readFile(path.join(out, "strings.ts"), "utf8")).toContain(
      '  "chest.opens": { left: number };'
    );
  });

  it("names the key and the file of a duration style it does not know", async () => {
    const root = await createRoot();
    const file = await write(root, "chest", "en", {
      "chest.opens": "Opens in {left, duration, tiny}"
    });

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `[game] i18n: "chest.opens" in ${file}: the duration style "tiny" is not supported.\n` +
        "  Fix the message or use a supported ICU feature."
    );
  });

  it("names both files when a parameter is a duration in one locale and a number in another", async () => {
    const root = await createRoot();
    const english = await write(root, "chest", "en", {
      "chest.opens": "Opens in {left, duration}"
    });
    const russian = await write(root, "chest", "ru", { "chest.opens": "Через {left, number}" });

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `"chest.opens": the parameter "left" is a duration in ${english} and a number in ${russian}.`
    );
  });
});

describe("compileStrings with translator notes", () => {
  const NOTE = "Button on an order card, max 10 chars";

  it("compiles a { text, note } value like its text", async () => {
    const root = await createRoot();
    const out = path.join(root, "generated");

    await write(root, "hud", "en", {
      "hud.deliver": { text: "Deliver", note: NOTE },
      "hud.orders": { text: ORDERS_EN },
      "hud.title": "Orders"
    });
    await compileStrings(root, out);

    const english = evaluateModule(await readFile(path.join(out, "strings.en.ts"), "utf8"));
    const kit = createIntlKit("en");

    expect(english["hud.deliver"]?.({}, kit)).toEqual([{ kind: "text", text: "Deliver" }]);
    expect(english["hud.orders"]?.({ n: 3 }, kit)).toEqual([{ kind: "text", text: "3 orders" }]);
  });

  it("writes the note into no generated byte", async () => {
    const root = await createRoot();
    const out = path.join(root, "generated");

    await write(root, "hud", "en", { "hud.deliver": { text: "Deliver", note: NOTE } });
    await write(root, "hud", "ru", { "hud.deliver": { text: "Отдать", note: NOTE } });
    await compileStrings(root, out, { pseudo: true });

    for (const name of ["strings.ts", "strings.en.ts", "strings.ru.ts", "strings.en-XA.ts"]) {
      const text = await readFile(path.join(out, name), "utf8");

      expect(text).not.toContain("max 10 chars");
      expect(text).not.toContain("note");
    }
  });

  it.each([
    ["a number", "3"],
    ["null", "null"],
    ["an array", '["Deliver"]'],
    ["an object without text", '{ "note": "Plank button" }'],
    ["a text that is not a string", '{ "text": 3 }'],
    ["a note that is not a string", '{ "text": "Deliver", "note": 10 }'],
    ["an extra member", '{ "text": "Deliver", "note": "Plank button", "max": 10 }']
  ])("refuses %s", async (_shape, value) => {
    const root = await createRoot();
    const file = await write(root, "hud", "en", `{ "hud.deliver": ${value} }\n`);

    await expect(compileStrings(root, path.join(root, "generated"))).rejects.toThrow(
      `[game] i18n: "hud.deliver" in ${file}: a message is a string or { "text": string, "note": string }.\n`
    );
  });
});

describe("compileStrings with the pseudo-locale", () => {
  it("writes strings.en-XA.ts from the English messages and lists en-XA", async () => {
    const { root, out } = await fixture();
    const report = await compileStrings(root, out, { pseudo: true });
    const pseudo = evaluateModule(await readFile(path.join(out, "strings.en-XA.ts"), "utf8"));
    const kit = createIntlKit("en-XA");

    expect(report.locales).toEqual(["en", "en-XA", "ru"]);
    expect(Object.keys(pseudo)).toEqual(["hud.coins", "hud.orders", "hud.title", "orders.coins"]);
    expect(pseudo["hud.title"]?.({}, kit)).toEqual([{ kind: "text", text: "[Óŕðéŕš one]" }]);
    expect(pseudo["hud.orders"]?.({ n: 3 }, kit)).toEqual([
      { kind: "text", text: "[3 óŕðéŕš one two]" }
    ]);
  });

  it("leaves the types module and the notes as they are without it", async () => {
    const { root, out } = await fixture();
    const report = await compileStrings(root, out, { pseudo: true });

    expect(await readFile(path.join(out, "strings.ts"), "utf8")).toBe(EXPECTED_TYPES);
    expect(report.notes).toEqual([
      'the key "settings.tab" is missing from features/settings/strings/en.json.'
    ]);
  });

  it("writes the same bytes on a second run", async () => {
    const { root, out } = await fixture();

    await compileStrings(root, out, { pseudo: true });

    const first = await readFile(path.join(out, "strings.en-XA.ts"), "utf8");
    const report = await compileStrings(root, out, { pseudo: true });

    expect(report.changed).toBe(false);
    expect(await readFile(path.join(out, "strings.en-XA.ts"), "utf8")).toBe(first);
  });

  it("checks strings.en-XA.ts on a check run with pseudo, and ignores it without", async () => {
    const { root, out } = await fixture();

    await compileStrings(root, out);

    const withPseudo = await compileStrings(root, out, { check: true, pseudo: true });
    const withoutPseudo = await compileStrings(root, out, { check: true });

    expect(withPseudo.changed).toBe(true);
    expect(withoutPseudo.changed).toBe(false);
    await expect(readFile(path.join(out, "strings.en-XA.ts"), "utf8")).rejects.toThrow();
  });

  it("refuses to run when no feature brings an English string file", async () => {
    const root = await createRoot();

    await write(root, "hud", "ru", { "hud.title": "Заказы" });

    await expect(
      compileStrings(root, path.join(root, "generated"), { pseudo: true })
    ).rejects.toThrow(
      '[game] i18n: "--pseudo" needs an "en" string file in at least one feature.\n' +
        '  Add features/<feature>/strings/en.json or drop "--pseudo".'
    );
    await expect(readFile(path.join(root, "generated", "strings.ts"), "utf8")).rejects.toThrow();
  });
});

describe("compileStrings with layers", () => {
  it("compiles the strings of a layer next to the features", async () => {
    const root = await createRoot();
    const out = path.join(root, "generated");

    await write(root, "hud", "en", { "hud.title": "Orders" });
    await writeIn(root, "shared", "en", { "ui.ok": "OK" });

    const report = await compileStrings(root, out, { layers: { shared: "ui" } });
    const english = evaluateModule(await readFile(path.join(out, "strings.en.ts"), "utf8"));

    expect(report.keys).toEqual(["hud.title", "ui.ok"]);
    expect(english["ui.ok"]?.({}, createIntlKit("en"))).toEqual([{ kind: "text", text: "OK" }]);
  });

  it("walks no layer by default", async () => {
    const root = await createRoot();

    await write(root, "hud", "en", { "hud.title": "Orders" });
    await writeIn(root, "shared", "en", { "ui.ok": "OK" });

    const report = await compileStrings(root, path.join(root, "generated"));

    expect(report.keys).toEqual(["hud.title"]);
  });

  it("reads nothing of a layer without a strings folder", async () => {
    const root = await createRoot();

    await write(root, "hud", "en", { "hud.title": "Orders" });

    const report = await compileStrings(root, path.join(root, "generated"), {
      layers: { shared: "ui" }
    });

    expect(report.keys).toEqual(["hud.title"]);
  });

  it("names both files when a layer and a feature carry the same key", async () => {
    const root = await createRoot();

    await writeIn(root, "shared", "en", { "hud.title": "Orders" });
    await write(root, "hud", "en", { "hud.title": "Orders" });

    await expect(
      compileStrings(root, path.join(root, "generated"), { layers: { shared: "ui" } })
    ).rejects.toThrow(
      'the key "hud.title" is in features/hud/strings/en.json and shared/strings/en.json.'
    );
  });

  it("names both layer files when two layers carry the same key", async () => {
    const root = await createRoot();

    await writeIn(root, "shared", "en", { "ui.ok": "OK" });
    await writeIn(root, "common", "en", { "ui.ok": "OK" });

    await expect(
      compileStrings(root, path.join(root, "generated"), {
        layers: { shared: "ui", common: "common" }
      })
    ).rejects.toThrow('the key "ui.ok" is in common/strings/en.json and shared/strings/en.json.');
  });

  it("names the layer file a locale lacks", async () => {
    const root = await createRoot();

    await write(root, "hud", "en", { "hud.title": "Orders" });
    await write(root, "hud", "ru", { "hud.title": "Заказы" });
    await writeIn(root, "shared", "en", { "ui.ok": "OK" });

    const report = await compileStrings(root, path.join(root, "generated"), {
      layers: { shared: "ui" }
    });

    expect(report.notes).toEqual(['the key "ui.ok" is missing from shared/strings/ru.json.']);
  });

  it("refuses a layer folder that is not one folder name, before a file is read or written", async () => {
    const outside = await createRoot();
    const root = path.join(outside, "game");
    const out = path.join(root, "generated");

    await write(root, "hud", "en", { "hud.title": "Orders" });
    await writeIn(outside, "other", "en", { "ui.ok": "OK" });

    await expect(compileStrings(root, out, { layers: { "../other": "ui" } })).rejects.toThrow(
      '[game] i18n: the layer "../other" is not a folder name.\n' +
        String.raw`  Use a name without "/", "\" or ".".`
    );
    await expect(
      compileStrings(root, out, { pseudo: true, layers: { "../other": "ui" } })
    ).rejects.toThrow('the layer "../other" is not a folder name.');

    for (const folder of ["", ".", "shared/ui", String.raw`shared\ui`]) {
      await expect(compileStrings(root, out, { layers: { [folder]: "ui" } })).rejects.toThrow(
        `the layer "${folder}" is not a folder name.`
      );
    }

    await expect(readFile(path.join(out, "strings.ts"), "utf8")).rejects.toThrow();
  });

  it("finds the English file of a layer for the pseudo-locale", async () => {
    const root = await createRoot();
    const out = path.join(root, "generated");

    await write(root, "hud", "ru", { "hud.title": "Заказы" });
    await writeIn(root, "shared", "en", { "ui.ok": "OK" });

    await expect(compileStrings(root, out, { pseudo: true })).rejects.toThrow(
      '"--pseudo" needs an "en" string file in at least one feature.'
    );

    const report = await compileStrings(root, out, { pseudo: true, layers: { shared: "ui" } });

    expect(report.locales).toEqual(["en", "en-XA", "ru"]);
  });

  it("names a file by the features folder the options name", async () => {
    const root = await createRoot();

    await writeIn(root, "mods/hud", "en", { "hud.price": "{n, number, currency}" });

    await expect(
      compileStrings(root, path.join(root, "generated"), { features: "mods" })
    ).rejects.toThrow(
      '[game] i18n: "hud.price" in mods/hud/strings/en.json: the number style "currency" is not supported.'
    );
  });

  it("names the missing file under the features folder the options name", async () => {
    const root = await createRoot();

    await writeIn(root, "mods/hud", "en", { "hud.title": "Orders" });
    await writeIn(root, "mods/shop", "ru", { "shop.title": "Магазин" });

    const report = await compileStrings(root, path.join(root, "generated"), { features: "mods" });

    expect(report.notes).toEqual([
      'the key "hud.title" is missing from mods/hud/strings/ru.json.',
      'the key "shop.title" is missing from mods/shop/strings/en.json.'
    ]);
  });
});
