import { describe, expect, it } from "vitest";
import { parseManifest } from "../../manifest";
import { emitKeys, emitManifest } from "../../scan/emit";
import type { Manifest } from "../../types";

const manifest: Manifest = {
  version: 1,
  bundles: {
    ui: {
      feature: "ui",
      tier: "core",
      mb: 0.188,
      files: [
        {
          key: "ui.panel",
          path: "features/ui/assets/panel{nine=48}.png",
          width: 256,
          height: 128,
          mb: 0.125,
          nine: { left: 48, top: 48, right: 48, bottom: 48 }
        },
        {
          key: "ui.button.primary",
          path: "features/ui/assets/button/primary.png",
          width: 128,
          height: 128,
          mb: 0.063
        }
      ]
    },
    board: { feature: "board", tier: "scene", mb: 0, files: [] }
  }
};

const empty: Manifest = { version: 1, bundles: {} };

describe("emitManifest", () => {
  it("writes the version, sorted bundles and sorted files with a trailing newline", () => {
    const text = emitManifest(manifest);

    expect(text.endsWith("}\n")).toBe(true);
    expect(text).toBe(`{
  "version": 1,
  "bundles": {
    "board": {
      "feature": "board",
      "tier": "scene",
      "mb": 0,
      "files": []
    },
    "ui": {
      "feature": "ui",
      "tier": "core",
      "mb": 0.188,
      "files": [
        {
          "key": "ui.button.primary",
          "path": "features/ui/assets/button/primary.png",
          "width": 128,
          "height": 128,
          "mb": 0.063
        },
        {
          "key": "ui.panel",
          "path": "features/ui/assets/panel{nine=48}.png",
          "width": 256,
          "height": 128,
          "mb": 0.125,
          "nine": {
            "left": 48,
            "top": 48,
            "right": 48,
            "bottom": 48
          }
        }
      ]
    }
  }
}
`);
  });

  it("is read back by the runtime parser", () => {
    const parsed = parseManifest(JSON.parse(emitManifest(manifest)) as unknown);

    expect(parsed.bundles.ui?.files[1]?.nine).toEqual({
      left: 48,
      top: 48,
      right: 48,
      bottom: 48
    });
  });

  it("drops a reserved atlas field, which this version never writes", () => {
    const withAtlas: Manifest = {
      version: 1,
      bundles: {
        ui: {
          feature: "ui",
          tier: "core",
          mb: 0,
          files: [
            {
              key: "ui.panel",
              path: "p.png",
              width: 8,
              height: 8,
              mb: 0,
              atlas: { page: "ui-0.png", x: 0, y: 0, width: 8, height: 8 }
            }
          ]
        }
      }
    };

    expect(emitManifest(withAtlas)).not.toContain("atlas");
  });

  it("writes an empty game as version 1 with no bundles", () => {
    expect(emitManifest(empty)).toBe('{\n  "version": 1,\n  "bundles": {}\n}\n');
  });
});

describe("emitKeys", () => {
  it("writes the header, both unions and the nine-slice table", () => {
    expect(emitKeys(manifest)).toBe(`// generated by @moku-labs/game/assets, do not edit

export type AssetKey =
  | "ui.button.primary"
  | "ui.panel";

export type BundleKey =
  | "board"
  | "ui";

export const nineSlice = {
  "ui.panel": { left: 48, top: 48, right: 48, bottom: 48 }
} as const;
`);
  });

  it("sorts the nine-slice table across bundles", () => {
    const borders = { left: 1, top: 2, right: 3, bottom: 4 };
    const two: Manifest = {
      version: 1,
      bundles: {
        ui: {
          feature: "ui",
          tier: "core",
          mb: 0,
          files: [{ key: "ui.panel", path: "p.png", width: 8, height: 8, mb: 0, nine: borders }]
        },
        board: {
          feature: "board",
          tier: "scene",
          mb: 0,
          files: [{ key: "board.slot", path: "s.png", width: 8, height: 8, mb: 0, nine: borders }]
        }
      }
    };

    expect(emitKeys(two)).toContain(
      '  "board.slot": { left: 1, top: 2, right: 3, bottom: 4 },\n' +
        '  "ui.panel": { left: 1, top: 2, right: 3, bottom: 4 }\n'
    );
  });

  it("writes never for an empty game", () => {
    expect(emitKeys(empty)).toBe(`// generated by @moku-labs/game/assets, do not edit

export type AssetKey = never;

export type BundleKey = never;

export const nineSlice = {} as const;
`);
  });
});
