/**
 * @file i18n plugin, build time — the two output kinds: the compiled module of one locale and
 * the types module a game's `defineGame` reads. Both are sorted and carry no timestamp and no
 * absolute path, so two compiles of the same files write the same bytes.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import type { CompiledSource, ParameterType } from "./message";

/** How every generated file starts. */
const HEADER = "// generated by @moku-labs/game/assets, do not edit";

/** The TypeScript cast keyword, kept apart so this file writes one and holds none. */
const CAST = "as";

/** How a key with no parameters is typed, so `tr` takes it with no second argument. */
const NO_PARAMS = "Record<string, never>";

/** The name of the union a plain argument is typed by. */
const ARGUMENT = "Argument";

/**
 * One key of the generated locale module.
 */
export type LocaleEntry = { key: string; compiled: CompiledSource };

/**
 * One key of the generated types module.
 */
export type TypeEntry = { key: string; params: Record<string, ParameterType> };

/**
 * The helper a compiled message calls for a plain argument: an element node keeps its place, a
 * list and a number go through `Intl`, everything else is read as text.
 *
 * @returns The helper as source.
 */
function argumentHelper(): string {
  return [
    "/** One plain argument: an element stays an element, a list and a number go through Intl. */",
    "function argument(value: unknown, intl: I18n.IntlKit): I18n.Part {",
    "  if (Array.isArray(value)) {",
    `    return { kind: "text", text: intl.list().format(value ${CAST} readonly string[]) };`,
    "  }",
    "",
    '  if (typeof value === "number") return { kind: "text", text: intl.number().format(value) };',
    "",
    "  if (",
    '    typeof value === "object" &&',
    "    value !== null &&",
    '    "type" in value &&',
    '    "props" in value &&',
    '    "children" in value',
    "  ) {",
    `    return { kind: "element", node: value ${CAST} I18n.ElementNode };`,
    "  }",
    "",
    '  return { kind: "text", text: String(value) };',
    "}"
  ].join("\n");
}

/**
 * Compares two keys, so every list the compiler writes has one order.
 *
 * @param left - First key.
 * @param right - Second key.
 * @returns The sort order.
 */
function byName(left: string, right: string): number {
  if (left === right) return 0;

  return left < right ? -1 : 1;
}

/**
 * Writes `generated/strings.<locale>.ts`: one arrow per key, keys sorted, the helper only when a
 * message needs it.
 *
 * @param entries - The keys of the locale, in any order.
 * @returns The text of the module.
 * @example
 * ```ts
 * emitLocale([{ key: "home.play", compiled: compileMessage("Играть") }]);
 * // the header, the import type and one key whose arrow returns one text part
 * ```
 */
export function emitLocale(entries: readonly LocaleEntry[]): string {
  const sorted = [...entries].toSorted((left, right) => byName(left.key, right.key));
  const rows = sorted.map(entry => `  ${JSON.stringify(entry.key)}: ${entry.compiled.source}`);
  const blocks = [`${HEADER}\nimport type { I18n } from "@moku-labs/game";`];

  if (sorted.some(entry => entry.compiled.usesArgument)) blocks.push(argumentHelper());

  blocks.push(`export default {\n${rows.join(",\n")}\n} satisfies I18n.CompiledMessages;`);

  return `${blocks.join("\n\n")}\n`;
}

/**
 * Writes the type of one parameter.
 *
 * @param type - What the compiler read for it.
 * @returns The TypeScript type.
 * @example
 * ```ts
 * typeOf({ kind: "select", options: ["audio"] }); // '"audio"'
 * ```
 */
function typeOf(type: ParameterType): string {
  if (type.kind === "argument") return ARGUMENT;
  if (type.kind === "number") return "number";
  if (type.kind === "date") return "Date | number";

  return type.options.map(option => JSON.stringify(option)).join(" | ");
}

/**
 * A parameter name as a type field: quoted when it is not a plain identifier, so the types module
 * compiles for the same names the locale module escapes.
 *
 * @param name - The parameter name of the message.
 * @returns The field name text.
 * @example
 * ```ts
 * fieldName("n"); // "n"
 * fieldName("a-b"); // "\"a-b\""
 * ```
 */
function fieldName(name: string): string {
  return /^[A-Za-z_$][\w$]*$/.test(name) ? name : JSON.stringify(name);
}

/**
 * Writes the parameters object of one key.
 *
 * @param params - The parameters the key declares.
 * @returns The TypeScript type of the parameters.
 */
function paramsOf(params: Record<string, ParameterType>): string {
  const names = Object.keys(params).toSorted(byName);

  if (names.length === 0) return NO_PARAMS;

  const fields = names.map(name => `${fieldName(name)}: ${typeOf(params[name] as ParameterType)}`);

  return `{ ${fields.join("; ")} }`;
}

/**
 * Writes `generated/strings.ts`: the key-to-parameters table a game passes to `defineGame`, and
 * the key union next to it. A key with a plain argument pulls in `DescriptionNode`, so an icon
 * may be passed where the message expects one.
 *
 * @param entries - Every key of the game, in any order.
 * @returns The text of the module.
 * @example
 * ```ts
 * emitTypes([{ key: "hud.orders", params: { n: { kind: "number" } } }]);
 * // the header and `export type Strings = { "hud.orders": { n: number } };`
 * ```
 */
export function emitTypes(entries: readonly TypeEntry[]): string {
  const sorted = [...entries].toSorted((left, right) => byName(left.key, right.key));
  const rows = sorted.map(entry => `  ${JSON.stringify(entry.key)}: ${paramsOf(entry.params)};`);
  const usesArgument = sorted.some(entry =>
    Object.values(entry.params).some(entry => entry.kind === "argument")
  );
  const blocks = usesArgument
    ? [
        `${HEADER}\nimport type { DescriptionNode } from "@moku-labs/game";`,
        `type ${ARGUMENT} = string | number | readonly string[] | DescriptionNode;`
      ]
    : [HEADER];

  blocks.push(
    `export type Strings = {\n${rows.join("\n")}\n};`,
    "export type StringKey = keyof Strings;"
  );

  return `${blocks.join("\n\n")}\n`;
}

/**
 * Reads an output file that may not exist yet.
 *
 * @param file - Path of the file.
 * @returns Its text, or `undefined` when it is not there.
 */
async function readCurrent(file: string): Promise<string | undefined> {
  try {
    return await readFile(file, "utf8");
  } catch {
    return undefined;
  }
}

/**
 * Writes one output file when its text changed, and tells whether it differed.
 *
 * @param file - Path of the file.
 * @param text - What it should contain.
 * @param write - False for a check run: nothing is written.
 * @returns True when the file on disk differs from the text.
 * @example
 * ```ts
 * await writeIfChanged("src/generated/strings.ts", "// generated\n", true); // true on the first run
 * ```
 */
export async function writeIfChanged(file: string, text: string, write: boolean): Promise<boolean> {
  if ((await readCurrent(file)) === text) return false;

  if (write) {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, text);
  }

  return true;
}
