// bun gen-scale.ts  ->  writes scale-generated.ts: 25 flows x 12 nodes = 300 nodes.
const FLOWS = 25;
let src = `// GENERATED by gen-scale.ts. ${FLOWS} flows x 12 nodes.\nimport { exit, slot, to, type } from "./graph";\nimport { defineFlow, defineNode, popup } from "./example-kit";\n`;

for (let i = 0; i < FLOWS; i++) {
  const p = `f${i}`;
  const nested = i % 5 !== 0; // chains of 5 nested sub-flows
  src += `
// ------------------------------------------------ flow ${i}
const ${p}n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % ${i + 2}; return out.done(); } });
const ${p}n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k${i}: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const ${p}n2 = defineNode({
  input: type<{ from: string; to: string; k${i}: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs${i}" })),
});
const ${p}n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < ${i + 1}) return out.noEnergy({ missing: ${i + 1} });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const ${p}n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave${i}", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const ${p}n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += ${i}; return out.done(); } });
const ${p}n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward${i}", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const ${p}n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const ${p}n8 = slot("after${i}");
const ${p}n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + ${i} })),
});
const ${p}n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });
${nested ? "" : `const ${p}n11 = defineNode({ rest: true, input: type<{ level: number }>(), outcomes: { leave: type(), won: type<{ stars: number }>() } });`}

export const flow${i} = defineFlow("flow${i}", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: ${p}n0, n1: ${p}n1, n2: ${p}n2, n3: ${p}n3, n4: ${p}n4, n5: ${p}n5, n6: ${p}n6, n7: ${p}n7, n8: ${p}n8, n9: ${p}n9, n10: ${p}n10, n11: ${nested ? `flow${i - 1}` : `${p}n11`} },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: ${i} })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});
`;
}
await Bun.write(new URL("./scale-generated.ts", import.meta.url).pathname, src);
console.log(`wrote scale-generated.ts: ${src.split("\n").length} lines`);
