// GENERATED by gen-scale.ts. 25 flows x 12 nodes.
import { exit, slot, to, type } from "./graph";
import { defineFlow, defineNode, popup } from "./example-kit";

// ------------------------------------------------ flow 0
const f0n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 2; return out.done(); } });
const f0n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k0: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f0n2 = defineNode({
  input: type<{ from: string; to: string; k0: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs0" })),
});
const f0n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 1) return out.noEnergy({ missing: 1 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f0n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave0", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f0n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 0; return out.done(); } });
const f0n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward0", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f0n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f0n8 = slot("after0");
const f0n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 0 })),
});
const f0n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });
const f0n11 = defineNode({ rest: true, input: type<{ level: number }>(), outcomes: { leave: type(), won: type<{ stars: number }>() } });

export const flow0 = defineFlow("flow0", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f0n0, n1: f0n1, n2: f0n2, n3: f0n3, n4: f0n4, n5: f0n5, n6: f0n6, n7: f0n7, n8: f0n8, n9: f0n9, n10: f0n10, n11: f0n11 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 0 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 1
const f1n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 3; return out.done(); } });
const f1n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k1: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f1n2 = defineNode({
  input: type<{ from: string; to: string; k1: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs1" })),
});
const f1n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 2) return out.noEnergy({ missing: 2 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f1n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave1", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f1n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 1; return out.done(); } });
const f1n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward1", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f1n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f1n8 = slot("after1");
const f1n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 1 })),
});
const f1n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow1 = defineFlow("flow1", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f1n0, n1: f1n1, n2: f1n2, n3: f1n3, n4: f1n4, n5: f1n5, n6: f1n6, n7: f1n7, n8: f1n8, n9: f1n9, n10: f1n10, n11: flow0 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 1 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 2
const f2n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 4; return out.done(); } });
const f2n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k2: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f2n2 = defineNode({
  input: type<{ from: string; to: string; k2: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs2" })),
});
const f2n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 3) return out.noEnergy({ missing: 3 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f2n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave2", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f2n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 2; return out.done(); } });
const f2n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward2", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f2n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f2n8 = slot("after2");
const f2n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 2 })),
});
const f2n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow2 = defineFlow("flow2", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f2n0, n1: f2n1, n2: f2n2, n3: f2n3, n4: f2n4, n5: f2n5, n6: f2n6, n7: f2n7, n8: f2n8, n9: f2n9, n10: f2n10, n11: flow1 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 2 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 3
const f3n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 5; return out.done(); } });
const f3n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k3: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f3n2 = defineNode({
  input: type<{ from: string; to: string; k3: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs3" })),
});
const f3n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 4) return out.noEnergy({ missing: 4 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f3n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave3", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f3n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 3; return out.done(); } });
const f3n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward3", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f3n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f3n8 = slot("after3");
const f3n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 3 })),
});
const f3n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow3 = defineFlow("flow3", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f3n0, n1: f3n1, n2: f3n2, n3: f3n3, n4: f3n4, n5: f3n5, n6: f3n6, n7: f3n7, n8: f3n8, n9: f3n9, n10: f3n10, n11: flow2 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 3 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 4
const f4n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 6; return out.done(); } });
const f4n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k4: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f4n2 = defineNode({
  input: type<{ from: string; to: string; k4: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs4" })),
});
const f4n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 5) return out.noEnergy({ missing: 5 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f4n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave4", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f4n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 4; return out.done(); } });
const f4n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward4", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f4n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f4n8 = slot("after4");
const f4n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 4 })),
});
const f4n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow4 = defineFlow("flow4", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f4n0, n1: f4n1, n2: f4n2, n3: f4n3, n4: f4n4, n5: f4n5, n6: f4n6, n7: f4n7, n8: f4n8, n9: f4n9, n10: f4n10, n11: flow3 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 4 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 5
const f5n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 7; return out.done(); } });
const f5n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k5: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f5n2 = defineNode({
  input: type<{ from: string; to: string; k5: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs5" })),
});
const f5n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 6) return out.noEnergy({ missing: 6 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f5n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave5", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f5n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 5; return out.done(); } });
const f5n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward5", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f5n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f5n8 = slot("after5");
const f5n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 5 })),
});
const f5n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });
const f5n11 = defineNode({ rest: true, input: type<{ level: number }>(), outcomes: { leave: type(), won: type<{ stars: number }>() } });

export const flow5 = defineFlow("flow5", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f5n0, n1: f5n1, n2: f5n2, n3: f5n3, n4: f5n4, n5: f5n5, n6: f5n6, n7: f5n7, n8: f5n8, n9: f5n9, n10: f5n10, n11: f5n11 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 5 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 6
const f6n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 8; return out.done(); } });
const f6n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k6: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f6n2 = defineNode({
  input: type<{ from: string; to: string; k6: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs6" })),
});
const f6n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 7) return out.noEnergy({ missing: 7 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f6n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave6", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f6n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 6; return out.done(); } });
const f6n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward6", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f6n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f6n8 = slot("after6");
const f6n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 6 })),
});
const f6n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow6 = defineFlow("flow6", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f6n0, n1: f6n1, n2: f6n2, n3: f6n3, n4: f6n4, n5: f6n5, n6: f6n6, n7: f6n7, n8: f6n8, n9: f6n9, n10: f6n10, n11: flow5 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 6 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 7
const f7n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 9; return out.done(); } });
const f7n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k7: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f7n2 = defineNode({
  input: type<{ from: string; to: string; k7: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs7" })),
});
const f7n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 8) return out.noEnergy({ missing: 8 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f7n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave7", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f7n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 7; return out.done(); } });
const f7n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward7", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f7n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f7n8 = slot("after7");
const f7n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 7 })),
});
const f7n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow7 = defineFlow("flow7", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f7n0, n1: f7n1, n2: f7n2, n3: f7n3, n4: f7n4, n5: f7n5, n6: f7n6, n7: f7n7, n8: f7n8, n9: f7n9, n10: f7n10, n11: flow6 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 7 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 8
const f8n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 10; return out.done(); } });
const f8n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k8: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f8n2 = defineNode({
  input: type<{ from: string; to: string; k8: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs8" })),
});
const f8n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 9) return out.noEnergy({ missing: 9 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f8n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave8", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f8n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 8; return out.done(); } });
const f8n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward8", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f8n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f8n8 = slot("after8");
const f8n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 8 })),
});
const f8n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow8 = defineFlow("flow8", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f8n0, n1: f8n1, n2: f8n2, n3: f8n3, n4: f8n4, n5: f8n5, n6: f8n6, n7: f8n7, n8: f8n8, n9: f8n9, n10: f8n10, n11: flow7 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 8 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 9
const f9n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 11; return out.done(); } });
const f9n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k9: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f9n2 = defineNode({
  input: type<{ from: string; to: string; k9: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs9" })),
});
const f9n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 10) return out.noEnergy({ missing: 10 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f9n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave9", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f9n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 9; return out.done(); } });
const f9n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward9", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f9n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f9n8 = slot("after9");
const f9n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 9 })),
});
const f9n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow9 = defineFlow("flow9", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f9n0, n1: f9n1, n2: f9n2, n3: f9n3, n4: f9n4, n5: f9n5, n6: f9n6, n7: f9n7, n8: f9n8, n9: f9n9, n10: f9n10, n11: flow8 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 9 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 10
const f10n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 12; return out.done(); } });
const f10n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k10: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f10n2 = defineNode({
  input: type<{ from: string; to: string; k10: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs10" })),
});
const f10n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 11) return out.noEnergy({ missing: 11 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f10n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave10", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f10n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 10; return out.done(); } });
const f10n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward10", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f10n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f10n8 = slot("after10");
const f10n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 10 })),
});
const f10n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });
const f10n11 = defineNode({ rest: true, input: type<{ level: number }>(), outcomes: { leave: type(), won: type<{ stars: number }>() } });

export const flow10 = defineFlow("flow10", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f10n0, n1: f10n1, n2: f10n2, n3: f10n3, n4: f10n4, n5: f10n5, n6: f10n6, n7: f10n7, n8: f10n8, n9: f10n9, n10: f10n10, n11: f10n11 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 10 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 11
const f11n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 13; return out.done(); } });
const f11n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k11: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f11n2 = defineNode({
  input: type<{ from: string; to: string; k11: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs11" })),
});
const f11n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 12) return out.noEnergy({ missing: 12 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f11n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave11", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f11n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 11; return out.done(); } });
const f11n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward11", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f11n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f11n8 = slot("after11");
const f11n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 11 })),
});
const f11n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow11 = defineFlow("flow11", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f11n0, n1: f11n1, n2: f11n2, n3: f11n3, n4: f11n4, n5: f11n5, n6: f11n6, n7: f11n7, n8: f11n8, n9: f11n9, n10: f11n10, n11: flow10 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 11 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 12
const f12n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 14; return out.done(); } });
const f12n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k12: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f12n2 = defineNode({
  input: type<{ from: string; to: string; k12: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs12" })),
});
const f12n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 13) return out.noEnergy({ missing: 13 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f12n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave12", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f12n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 12; return out.done(); } });
const f12n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward12", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f12n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f12n8 = slot("after12");
const f12n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 12 })),
});
const f12n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow12 = defineFlow("flow12", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f12n0, n1: f12n1, n2: f12n2, n3: f12n3, n4: f12n4, n5: f12n5, n6: f12n6, n7: f12n7, n8: f12n8, n9: f12n9, n10: f12n10, n11: flow11 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 12 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 13
const f13n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 15; return out.done(); } });
const f13n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k13: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f13n2 = defineNode({
  input: type<{ from: string; to: string; k13: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs13" })),
});
const f13n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 14) return out.noEnergy({ missing: 14 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f13n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave13", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f13n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 13; return out.done(); } });
const f13n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward13", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f13n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f13n8 = slot("after13");
const f13n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 13 })),
});
const f13n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow13 = defineFlow("flow13", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f13n0, n1: f13n1, n2: f13n2, n3: f13n3, n4: f13n4, n5: f13n5, n6: f13n6, n7: f13n7, n8: f13n8, n9: f13n9, n10: f13n10, n11: flow12 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 13 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 14
const f14n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 16; return out.done(); } });
const f14n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k14: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f14n2 = defineNode({
  input: type<{ from: string; to: string; k14: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs14" })),
});
const f14n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 15) return out.noEnergy({ missing: 15 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f14n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave14", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f14n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 14; return out.done(); } });
const f14n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward14", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f14n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f14n8 = slot("after14");
const f14n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 14 })),
});
const f14n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow14 = defineFlow("flow14", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f14n0, n1: f14n1, n2: f14n2, n3: f14n3, n4: f14n4, n5: f14n5, n6: f14n6, n7: f14n7, n8: f14n8, n9: f14n9, n10: f14n10, n11: flow13 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 14 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 15
const f15n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 17; return out.done(); } });
const f15n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k15: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f15n2 = defineNode({
  input: type<{ from: string; to: string; k15: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs15" })),
});
const f15n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 16) return out.noEnergy({ missing: 16 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f15n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave15", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f15n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 15; return out.done(); } });
const f15n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward15", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f15n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f15n8 = slot("after15");
const f15n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 15 })),
});
const f15n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });
const f15n11 = defineNode({ rest: true, input: type<{ level: number }>(), outcomes: { leave: type(), won: type<{ stars: number }>() } });

export const flow15 = defineFlow("flow15", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f15n0, n1: f15n1, n2: f15n2, n3: f15n3, n4: f15n4, n5: f15n5, n6: f15n6, n7: f15n7, n8: f15n8, n9: f15n9, n10: f15n10, n11: f15n11 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 15 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 16
const f16n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 18; return out.done(); } });
const f16n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k16: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f16n2 = defineNode({
  input: type<{ from: string; to: string; k16: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs16" })),
});
const f16n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 17) return out.noEnergy({ missing: 17 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f16n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave16", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f16n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 16; return out.done(); } });
const f16n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward16", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f16n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f16n8 = slot("after16");
const f16n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 16 })),
});
const f16n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow16 = defineFlow("flow16", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f16n0, n1: f16n1, n2: f16n2, n3: f16n3, n4: f16n4, n5: f16n5, n6: f16n6, n7: f16n7, n8: f16n8, n9: f16n9, n10: f16n10, n11: flow15 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 16 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 17
const f17n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 19; return out.done(); } });
const f17n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k17: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f17n2 = defineNode({
  input: type<{ from: string; to: string; k17: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs17" })),
});
const f17n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 18) return out.noEnergy({ missing: 18 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f17n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave17", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f17n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 17; return out.done(); } });
const f17n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward17", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f17n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f17n8 = slot("after17");
const f17n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 17 })),
});
const f17n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow17 = defineFlow("flow17", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f17n0, n1: f17n1, n2: f17n2, n3: f17n3, n4: f17n4, n5: f17n5, n6: f17n6, n7: f17n7, n8: f17n8, n9: f17n9, n10: f17n10, n11: flow16 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 17 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 18
const f18n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 20; return out.done(); } });
const f18n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k18: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f18n2 = defineNode({
  input: type<{ from: string; to: string; k18: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs18" })),
});
const f18n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 19) return out.noEnergy({ missing: 19 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f18n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave18", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f18n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 18; return out.done(); } });
const f18n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward18", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f18n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f18n8 = slot("after18");
const f18n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 18 })),
});
const f18n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow18 = defineFlow("flow18", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f18n0, n1: f18n1, n2: f18n2, n3: f18n3, n4: f18n4, n5: f18n5, n6: f18n6, n7: f18n7, n8: f18n8, n9: f18n9, n10: f18n10, n11: flow17 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 18 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 19
const f19n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 21; return out.done(); } });
const f19n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k19: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f19n2 = defineNode({
  input: type<{ from: string; to: string; k19: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs19" })),
});
const f19n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 20) return out.noEnergy({ missing: 20 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f19n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave19", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f19n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 19; return out.done(); } });
const f19n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward19", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f19n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f19n8 = slot("after19");
const f19n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 19 })),
});
const f19n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow19 = defineFlow("flow19", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f19n0, n1: f19n1, n2: f19n2, n3: f19n3, n4: f19n4, n5: f19n5, n6: f19n6, n7: f19n7, n8: f19n8, n9: f19n9, n10: f19n10, n11: flow18 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 19 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 20
const f20n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 22; return out.done(); } });
const f20n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k20: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f20n2 = defineNode({
  input: type<{ from: string; to: string; k20: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs20" })),
});
const f20n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 21) return out.noEnergy({ missing: 21 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f20n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave20", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f20n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 20; return out.done(); } });
const f20n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward20", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f20n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f20n8 = slot("after20");
const f20n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 20 })),
});
const f20n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });
const f20n11 = defineNode({ rest: true, input: type<{ level: number }>(), outcomes: { leave: type(), won: type<{ stars: number }>() } });

export const flow20 = defineFlow("flow20", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f20n0, n1: f20n1, n2: f20n2, n3: f20n3, n4: f20n4, n5: f20n5, n6: f20n6, n7: f20n7, n8: f20n8, n9: f20n9, n10: f20n10, n11: f20n11 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 20 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 21
const f21n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 23; return out.done(); } });
const f21n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k21: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f21n2 = defineNode({
  input: type<{ from: string; to: string; k21: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs21" })),
});
const f21n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 22) return out.noEnergy({ missing: 22 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f21n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave21", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f21n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 21; return out.done(); } });
const f21n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward21", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f21n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f21n8 = slot("after21");
const f21n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 21 })),
});
const f21n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow21 = defineFlow("flow21", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f21n0, n1: f21n1, n2: f21n2, n3: f21n3, n4: f21n4, n5: f21n5, n6: f21n6, n7: f21n7, n8: f21n8, n9: f21n9, n10: f21n10, n11: flow20 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 21 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 22
const f22n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 24; return out.done(); } });
const f22n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k22: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f22n2 = defineNode({
  input: type<{ from: string; to: string; k22: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs22" })),
});
const f22n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 23) return out.noEnergy({ missing: 23 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f22n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave22", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f22n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 22; return out.done(); } });
const f22n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward22", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f22n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f22n8 = slot("after22");
const f22n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 22 })),
});
const f22n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow22 = defineFlow("flow22", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f22n0, n1: f22n1, n2: f22n2, n3: f22n3, n4: f22n4, n5: f22n5, n6: f22n6, n7: f22n7, n8: f22n8, n9: f22n9, n10: f22n10, n11: flow21 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 22 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 23
const f23n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 25; return out.done(); } });
const f23n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k23: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f23n2 = defineNode({
  input: type<{ from: string; to: string; k23: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs23" })),
});
const f23n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 24) return out.noEnergy({ missing: 24 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f23n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave23", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f23n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 23; return out.done(); } });
const f23n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward23", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f23n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f23n8 = slot("after23");
const f23n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 23 })),
});
const f23n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow23 = defineFlow("flow23", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f23n0, n1: f23n1, n2: f23n2, n3: f23n3, n4: f23n4, n5: f23n5, n6: f23n6, n7: f23n7, n8: f23n8, n9: f23n9, n10: f23n10, n11: flow22 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 23 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});

// ------------------------------------------------ flow 24
const f24n0 = defineNode({ outcomes: { done: type() }, run: ({ player, now, out }) => { player.wallet.energy += now % 26; return out.done(); } });
const f24n1 = defineNode({
  rest: true, checkpoint: true, inbox: ["elapsed"],
  outcomes: {
    move: type<{ from: string; to: string; k24: number }>(), tap: type<{ id: string }>(),
    give: type<{ item: string; order: number }>(), sell: type<{ item: string }>(),
    elapsed: type<{ now: number }>(), check: type(), sub: type(), leave: type(),
  },
});
const f24n2 = defineNode({
  input: type<{ from: string; to: string; k24: number }>(),
  outcomes: { done: type(), rejected: type<{ reason: string }>() },
  run: ({ player, input, out }) => (player.board[input.from] === player.board[input.to] ? out.done() : out.rejected({ reason: "differs24" })),
});
const f24n3 = defineNode({
  input: type<{ id: string }>(),
  outcomes: { done: type(), noEnergy: type<{ missing: number }>(), full: type() },
  run: ({ player, input, rng, out }) => {
    if (player.wallet.energy < 25) return out.noEnergy({ missing: 25 });
    if (rng.stream(input.id).int(0, 9) === 0) return out.full();
    return out.done();
  },
});
const f24n4 = defineNode({
  input: type<{ item: string; order: number }>(),
  outcomes: { done: type(), complete: type<{ rewardId: string }>() },
  run: ({ input, fx, out }) => { fx.emit({ kind: "gave24", data: input }); return input.order % 2 ? out.done() : out.complete({ rewardId: "r" + input.order }); },
});
const f24n5 = defineNode({ input: type<{ item: string }>(), outcomes: { done: type() }, run: ({ player, out }) => { player.wallet.coins += 24; return out.done(); } });
const f24n6 = defineNode({
  rest: true, over: true, input: type<{ rewardId: string; doubled: boolean }>(),
  outcomes: { claim: type(), double: type<{ rewardId: string }>() },
  run: async ({ fx, input, out }) => ((await fx(popup("Reward24", ["claim", "double"]))) === "claim" ? out.claim() : out.double({ rewardId: input.rewardId })),
});
const f24n7 = defineNode({ rest: true, over: true, input: type<{ missing: number }>(), outcomes: { close: type(), leave: type() } });
const f24n8 = slot("after24");
const f24n9 = defineNode({
  outcomes: { ok: type<{ level: number }>(), none: type<{ nextLifeAt: number }>() },
  run: ({ player, now, out }) => (player.lives > 0 ? out.ok({ level: player.level }) : out.none({ nextLifeAt: now + 24 })),
});
const f24n10 = defineNode({ rest: true, over: true, input: type<{ why: string }>(), outcomes: { again: type(), won: type<{ stars: number }>() } });


export const flow24 = defineFlow("flow24", {
  input: type<{ level: number }>(),
  outcomes: { leave: type(), won: type<{ stars: number }>() },
  nodes: { n0: f24n0, n1: f24n1, n2: f24n2, n3: f24n3, n4: f24n4, n5: f24n5, n6: f24n6, n7: f24n7, n8: f24n8, n9: f24n9, n10: f24n10, n11: flow23 },
  start: "n0",
  edges: {
    n0: { done: "n1" },
    n1: { move: "n2", tap: "n3", give: "n4", sell: "n5", elapsed: "n0", check: "n9", sub: to("n11", () => ({ level: 24 })), leave: exit("leave") },
    n2: { done: "n1", rejected: to("n10", (r: { reason: string }) => ({ why: r.reason })) },
    n3: { done: "n1", noEnergy: "n7", full: "n1" },
    n4: { done: "n1", complete: to("n6", (c: { rewardId: string }) => ({ rewardId: c.rewardId, doubled: false })) },
    n5: { done: "n8" },
    n6: { claim: "n1", double: to("n6", (c: { rewardId: string }) => ({ ...c, doubled: true })) },
    n7: { close: "n1", leave: exit("leave") },
    n8: { done: "n1" },
    n9: { ok: "n11", none: to("n10", (n: { nextLifeAt: number }) => ({ why: "lives@" + n.nextLifeAt })) },
    n10: { again: "n9", won: exit("won") },
    n11: { leave: "n1", won: exit("won") },
  },
});
